###register request
POST  http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "ali1997313",
    "email": "ali.rakhshanipour.sru@gmail.com",
    "phone": "09120397539",
    "password": "ali121212",
    "password_confirmation":"ali121212"
}

###login request
POST  http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{$dotenv SECRET_KEY_SHA1}}

{
    "username": "ali1997313",
    "password": "ali121212"
}