###register request
POST  http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "sssss",
    "email": "ali@gmail.com",
    "phone": "09123454323",
    "password": "ssssss",
    "password_confirmation":"ssssss"
}