###register request
POST  http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "saraawwwskari",
    "email": "sara_sssaskari@gmail.com",
    "phone": "09113495916",
    "password": "zahra5926",
    "password_confirmation":"zahra5926"
}

###login request
POST  http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{$dotenv SECRET_KEY_SHA1}}

{
    "username": "saraawwwskari",
    "password": "zahra5926"
}